workspace: "/Users/nathanreginato/Pictures/photoTest"
file-structure:
  - year
#- event
  - month-day
  - camera-type
  - photo-video
photo-process:
  - File type
  - Bests
  - Instagram
video-process:
  - File type
  - Bests
  - Instagram
aliases:
  x-canon-cr2: RAW
