workspace: "/Users/nathanreginato/Pictures/photoTest"
file-structure:
  - month-day
#- event
  - year
  - type
  - camera-type
  - ext
  - ext
aliases:
  x-canon-cr2: RAW
photo-process:
  - File type
  - Bests
  - Instagram
video-process:
  - File type
  - Bests
  - Instagram
